[package]
name = "tools"
version = "0.1.0"
authors = ["Vladas Zakrevksis <146100@gmail.com>"]
edition = "2021"

[dependencies]
dirs = "3.0.2"
tokio = { version = "1", features = ["full"] }
regex = "1.4.5"
serde = { version = "1.0.126", features = ["derive"]}
serde_json = "1.0.64"
num-traits = "0.2.14"
path-absolutize = "3.0.11"
