[package]
name = "tools"
version = "0.1.0"
authors = ["Vladas Zakrevksis <146100@gmail.com>"]
edition = "2021"

[dependencies]
log = "0"
cfg-if = "1"
dirs = "3"
tokio = { version = "1", features = ["full"] }
regex = "1"
serde = { version = "1", features = ["derive"]}
futures = "0"
serde_json = "1"
num-traits = "0"
path-absolutize = "3"

[target.'cfg(windows)'.dependencies.windows]
version = "0"
features = [
    "alloc",
    "Data_Xml_Dom",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Diagnostics_Debug",
]

[target.'cfg(target_os="android")'.dependencies]
android-ndk-sys = "0"